working on adding git repo pulling to the equation

diff --git a/odoo/templates/odoo-init.yaml b/odoo/templates/odoo-init.yaml
--- a/odoo/templates/odoo-init.yaml
+++ b/odoo/templates/odoo-init.yaml
@@ -110,3 +110,79 @@ data:
     END
     \$\$;
     EOSQL
+
+---
+
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: git-pull-addons
+  namespace: {{ .Release.Namespace }}
+data:
+  git-pull-addons.sh: |
+    #!/bin/bash
+    set -e
+
+    #!/bin/bash
+    set -e
+
+    REPO_DIR="/mnt/repo"
+    EXTRA_ADDONS_DIR="/mnt/extra-addons"
+
+    # Clear the /mnt/extra-addons directory
+    rm -rf $EXTRA_ADDONS_DIR/*
+    mkdir -p $EXTRA_ADDONS_DIR
+
+    # Function to clone or update a repo
+    clone_or_update_repo() {
+      local repo_url=$1
+      local branch=$2
+      local commit=$3
+      local target_dir=$4
+
+      if [ -d "$target_dir/.git" ]; then
+        echo "Repository $repo_url already exists. Fetching latest changes."
+        cd $target_dir
+        git fetch origin $branch
+        if [ -n "$commit" ]; then
+          git reset --hard $commit
+        else
+          git reset --hard origin/$branch
+        fi
+      else
+        echo "Cloning repository $repo_url."
+        git clone --recursive -b $branch $repo_url $target_dir
+        cd $target_dir
+        if [ -n "$commit" ]; then
+          git reset --hard $commit
+        fi
+      fi
+
+      # Update and initialize submodules
+      echo "Updating submodules for $repo_url..."
+      if ! git submodule update --init --recursive; then
+        echo "Submodule update failed. Attempting to reset submodules..."
+        git submodule deinit --all --force
+        git submodule sync --recursive
+        git submodule update --init --recursive --force
+        if ! git submodule update --init --recursive --force; then
+          echo "Submodule update failed after retry. Cleaning and reinitializing submodules."
+          git submodule foreach --recursive 'rm -rf $toplevel/$sm_path'
+          git submodule update --init --recursive --force
+        fi
+      fi
+      echo "Submodules updated successfully for $repo_url."
+    }
+
+    # Clone or update the main Odoo repository
+    clone_or_update_repo $REPO_URL $BRANCH $COMMIT $REPO_DIR
+
+    # Optionally clone or update the Odoo enterprise repository
+    if [ -n "$ENTERPRISE_BRANCH" ] || [ -n "$ENTERPRISE_COMMIT" ]; then
+      ENTERPRISE_REPO_URL="git@github.com:odoo/enterprise.git"
+      clone_or_update_repo $ENTERPRISE_REPO_URL $ENTERPRISE_BRANCH $ENTERPRISE_COMMIT "$REPO_DIR/enterprise"
+      ln -s "$REPO_DIR/enterprise/*" "$EXTRA_ADDONS_DIR/"
+    fi
+
+    # Link addons from the main repo to /mnt/extra-addons
+    ln -s "$REPO_DIR/addons/*" "$EXTRA_ADDONS_DIR/"
