Try to fix git pull init script

diff --git a/odoo/templates/odoo-init.yaml b/odoo/templates/odoo-init.yaml
--- a/odoo/templates/odoo-init.yaml
+++ b/odoo/templates/odoo-init.yaml
@@ -158,43 +158,43 @@ data:
 
     # Function to clone or update a repo
     clone_or_update_repo() {
-      local repo_url=$1
-      local branch=$2
-      local commit=$3
-      local target_dir=$4
+      local repo_url="$1"
+      local branch="$2"
+      local commit="$3"
+      local target_dir="$4"
 
       if [ -d "$target_dir/.git" ]; then
         echo "Repository $repo_url already exists. Fetching latest changes."
-        cd $target_dir
-        git fetch origin $branch
+        cd "$target_dir"
+        git fetch origin "$branch"
         if [ -n "$commit" ]; then
-          git reset --hard $commit
+          git reset --hard "$commit"
         else
           git reset --hard origin/$branch
         fi
       else
         echo "Cloning repository $repo_url."
-        git clone --recursive -b $branch $repo_url $target_dir
-        cd $target_dir
+        git clone --depth 1 --shalow-submodules -b "$branch" "$repo_url" "$target_dir"
+        cd "$target_dir"
         if [ -n "$commit" ]; then
           git reset --hard $commit
         fi
       fi
 
-      # Update and initialize submodules
-      echo "Updating submodules for $repo_url..."
-      if ! git submodule update --init --recursive; then
-        echo "Submodule update failed. Attempting to reset submodules..."
-        git submodule deinit --all --force
-        git submodule sync --recursive
-        git submodule update --init --recursive --force
-        if ! git submodule update --init --recursive --force; then
-          echo "Submodule update failed after retry. Cleaning and reinitializing submodules."
-          git submodule foreach --recursive 'rm -rf $toplevel/$sm_path'
-          git submodule update --init --recursive --force
-        fi
-      fi
-      echo "Submodules updated successfully for $repo_url."
+      # # Update and initialize submodules
+      # echo "Updating submodules for $repo_url..."
+      # if ! git submodule update --init --recursive; then
+      #   echo "Submodule update failed. Attempting to reset submodules..."
+      #   git submodule deinit --all --force
+      #   git submodule sync --recursive
+      #   git submodule update --init --recursive --force
+      #   if ! git submodule update --init --recursive --force; then
+      #     echo "Submodule update failed after retry. Cleaning and reinitializing submodules."
+      #     git submodule foreach --recursive 'rm -rf $toplevel/$sm_path'
+      #     git submodule update --init --recursive --force
+      #   fi
+      # fi
+      # echo "Submodules updated successfully for $repo_url."
     }
 
     # Clone or update the main Odoo repository
@@ -204,9 +204,8 @@ data:
 
     # Optionally clone or update the Odoo enterprise repository
     if [ -n "$ENTERPRISE_REPO_URL" ]; then
-
       # ssh-keyscan github.com >> $SSH_DIR/known_hosts
-      clone_or_update_repo $ENTERPRISE_REPO_URL $ENTERPRISE_BRANCH $ENTERPRISE_COMMIT "$REPO_DIR/enterprise"
+      clone_or_update_repo "$ENTERPRISE_REPO_URL" "$ENTERPRISE_BRANCH" "$ENTERPRISE_COMMIT" "$REPO_DIR/enterprise"
       ln -s "$REPO_DIR/enterprise/*" "$EXTRA_ADDONS_DIR/"
     fi
 
